import type { Estate, ParcelCollection } from "@/types";
import oyibi from "./parcels/oyibi-hillcrest.json";
import ejisu from "./parcels/ejisu-royal.json";
import sagnarigu from "./parcels/sagnarigu-green.json";

/**
 * Estate metadata + parcel GeoJSON (generated by scripts/generate-parcels.mjs).
 * Parcel *status overrides* (e.g. after a simulated purchase) live in the mock DB,
 * not here — merge via `applyParcelOverrides` in the service layer.
 */
export const ESTATES: Estate[] = [
  {
    id: "oyibi-hillcrest",
    name: "Oyibi Hillcrest Gardens",
    region: "Greater Accra",
    city: "Oyibi",
    center: { lat: 5.8265, lng: -0.0866 },
    zoom: 16.4,
    listingId: "lst-001",
    description:
      "A gated, fully-surveyed estate on the Adenta–Dodowa corridor with tarred access roads, electricity and piped water at every plot boundary.",
  },
  {
    id: "ejisu-royal",
    name: "Ejisu Royal Meadows",
    region: "Ashanti",
    city: "Ejisu, Kumasi",
    center: { lat: 6.7196, lng: -1.4738 },
    zoom: 16.4,
    listingId: "lst-002",
    description:
      "Serviced residential plots 15 minutes from Kumasi city centre, registered with the Lands Commission with an approved layout plan.",
  },
  {
    id: "sagnarigu-green",
    name: "Sagnarigu Greenfields",
    region: "Northern",
    city: "Tamale",
    center: { lat: 9.4433, lng: -0.8983 },
    zoom: 16.6,
    listingId: "lst-003",
    description:
      "Affordable greenfield plots in Tamale's fastest-growing suburb, ideal for first-time buyers and long-term investors.",
  },
];

const COLLECTIONS: Record<string, ParcelCollection> = {
  "oyibi-hillcrest": oyibi as ParcelCollection,
  "ejisu-royal": ejisu as ParcelCollection,
  "sagnarigu-green": sagnarigu as ParcelCollection,
};

export function getEstate(id: string): Estate | undefined {
  return ESTATES.find((e) => e.id === id);
}

export function getParcelCollection(estateId: string): ParcelCollection | undefined {
  return COLLECTIONS[estateId];
}
